services:
  - type: background
    name: okama-finance-bot
    env: python
    plan: starter
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
    autoDeploy: true
