name: Deploy to Production (Render)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    # Деплой только если PR был merged (не просто закрыт)
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Deploy to Production (Render)
      env:
        RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      run: |
        # Автоматическое развертывание на Render Production
        echo "🚀 Deploying to Render Production..."
        
        # Проверка статуса сервиса
        curl -H "Authorization: Bearer $RENDER_TOKEN" \
             "https://api.render.com/v1/services/$RENDER_SERVICE_ID" \
             | jq '.status'
             
        # Запуск деплоя
        curl -X POST \
             -H "Authorization: Bearer $RENDER_TOKEN" \
             -H "Content-Type: application/json" \
             "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys"
             
        echo "✅ Production deployment triggered successfully!"
        
    - name: Notify deployment status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "🎉 Production deployment completed successfully!"
        else
          echo "❌ Production deployment failed!"
        fi
