name: Deploy to Development (Render)

on:
  push:
    branches: [ DEV ]
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Deploy to Development (Render)
      env:
        RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
        RENDER_DEV_SERVICE_ID: ${{ secrets.RENDER_DEV_SERVICE_ID }}
      run: |
        # Автоматическое развертывание на Render Development
        echo "🚀 Deploying to Render Development..."
        
        # Проверка статуса сервиса
        curl -H "Authorization: Bearer $RENDER_TOKEN" \
             "https://api.render.com/v1/services/$RENDER_DEV_SERVICE_ID" \
             | jq '.status'
             
        # Запуск деплоя
        curl -X POST \
             -H "Authorization: Bearer $RENDER_TOKEN" \
             -H "Content-Type: application/json" \
             "https://api.render.com/v1/services/$RENDER_DEV_SERVICE_ID/deploys"
             
        echo "✅ Development deployment triggered successfully!"
        
    - name: Notify deployment status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "🎉 Development deployment completed successfully!"
        else
          echo "❌ Development deployment failed!"
        fi
